import sizes from "@/content/media-sizes.json";

/** Natural size of an image in public/media (generated by scripts/media-sizes.mjs), or null when unknown. */
export function mediaSize(src: string | null | undefined): { w: number; h: number } | null {
  const hit = src ? (sizes as Record<string, number[]>)[src] : undefined;
  return hit ? { w: hit[0], h: hit[1] } : null;
}
