import sizes from "@/content/doc-sizes.json";

/** Size in bytes of a file in public/docs (generated by scripts/doc-sizes.mjs), or null when it is not known. */
export function docBytes(href: string | null | undefined): number | null {
  return (href ? (sizes as Record<string, number>)[href] : undefined) ?? null;
}

/** What a download weighs, in the reader's number format and in the units file managers use: "225 KB", "1,3 MB". */
export function formatBytes(bytes: number, locale: string) {
  const number = (n: number, digits: number) => new Intl.NumberFormat(locale, { maximumFractionDigits: digits }).format(n);
  return bytes >= 1e6 ? `${number(bytes / 1e6, 1)} MB` : `${number(Math.max(1, bytes / 1e3), 0)} KB`;
}
